import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <div className='flex gap-4'>
          <Link href="/" className="text-rose-500 text-2xl">home</Link>
          <Link href="/testa" className="text-rose-500 text-2xl">testa</Link>
          <Link href="/testb" className="text-rose-500 text-2xl">testb</Link>
        </div>
        <>
          {children}
        </>
      </body>
    </html>
  )
}
